### ISSUE TITLE
get_svd_weight() -> if 'S' in svd_config:

### ISSUE THREAD

**Issue by ghost** [e-271/few-shot-gan#1]
please see below
<img width="1059" alt="Screen Shot 2020-10-23 at 11 12 34 AM" src="https://user-images.githubusercontent.com/6818285/97021460-db75cf80-1520-11eb-9070-7e055ad65d55.png">

**Comment by ghost** [comment]
was able to continue by doing
pdb.set_trace = lambda: None
continue

**Comment by e-271** [comment]
Fixed.
